export const FakeListItemSearchBorrow = [
  {
    associatedWalletAddress: '0x4f1918df034b1a7c24ff0c9be4eb8b96d48376f9',
    id: 8,
    name: 'Sushi Pawnshop',
    pawnShop: {
      id: 283,
      userId: 5741,
      name: 'Sushi Pawnshop',
      email: 'defiforyou2021@gmail.com',
      phoneNumber: '+84966963892',
      address: 'Hung Yen',
      description: "Let's go with us !",
      avatar: 'https://i.ytimg.com/vi/E5yeL6cFYjo/maxresdefault.jpg',
      reputation: 7,
      isFeaturedPawnshop: true,
      type: 1,
      rank: null,
      associatedAddress: null,
      completedContracts: null,
      minInterestRate: null,
      maxInterestRate: null,
      createdAt: '2021-07-12T06:19:49.658+00:00',
      updatedAt: '2021-10-01T13:56:36.703+00:00',
      isDeleted: false,
      medals: null,
      p2PLenderPackages: null,
      coverImage: null,
    },
    type: 1,
    acceptableAssetsAsCollateral: [
      {
        id: 38,
        isWhitelistCollateral: true,
        isWhitelistSupply: false,
        usdExchange: null,
        isAcceptedAsCollateral: true,
        isAcceptedAsLoan: null,
        isAcceptedRepayment: null,
        symbol: 'BNB',
        address: '0x0000000000000000000000000000000000000000',
      },
      {
        id: 8,
        isWhitelistCollateral: true,
        isWhitelistSupply: false,
        usdExchange: null,
        isAcceptedAsCollateral: true,
        isAcceptedAsLoan: null,
        isAcceptedRepayment: null,
        symbol: 'ETC',
        address: '0x3d6545b08693daE087E957cb1180ee38B9e3c25E',
      },
      {
        id: 9,
        isWhitelistCollateral: true,
        isWhitelistSupply: false,
        usdExchange: null,
        isAcceptedAsCollateral: true,
        isAcceptedAsLoan: null,
        isAcceptedRepayment: null,
        symbol: 'ZEC',
        address: '0x1Ba42e5193dfA8B03D15dd1B86a3113bbBEF8Eeb',
      },
      {
        id: 6,
        isWhitelistCollateral: true,
        isWhitelistSupply: false,
        usdExchange: null,
        isAcceptedAsCollateral: true,
        isAcceptedAsLoan: null,
        isAcceptedRepayment: null,
        symbol: 'XRP',
        address: '0x1D2F0da169ceB9fC7B3144628dB156f3F6c60dBE',
      },
      {
        id: 7,
        isWhitelistCollateral: true,
        isWhitelistSupply: false,
        usdExchange: null,
        isAcceptedAsCollateral: true,
        isAcceptedAsLoan: null,
        isAcceptedRepayment: null,
        symbol: 'LTC',
        address: '0x4338665CBB7B2485A8855A139b75D5e34AB0DB94',
      },
      {
        id: 10,
        isWhitelistCollateral: true,
        isWhitelistSupply: false,
        usdExchange: null,
        isAcceptedAsCollateral: true,
        isAcceptedAsLoan: null,
        isAcceptedRepayment: null,
        symbol: 'MKR',
        address: '0x5f0Da599BB2ccCfcf6Fdfd7D81743B6020864350',
      },
      {
        id: 11,
        isWhitelistCollateral: true,
        isWhitelistSupply: false,
        usdExchange: null,
        isAcceptedAsCollateral: true,
        isAcceptedAsLoan: null,
        isAcceptedRepayment: null,
        symbol: 'BAT',
        address: '0x101d82428437127bF1608F699CD651e6Abf9766E',
      },
      {
        id: 1,
        isWhitelistCollateral: true,
        isWhitelistSupply: true,
        usdExchange: null,
        isAcceptedAsCollateral: true,
        isAcceptedAsLoan: null,
        isAcceptedRepayment: true,
        symbol: 'DFY',
        address: '0xD98560689C6e748DC37bc410B4d3096B1aA3D8C2',
      },
      {
        id: 2,
        isWhitelistCollateral: true,
        isWhitelistSupply: false,
        usdExchange: null,
        isAcceptedAsCollateral: true,
        isAcceptedAsLoan: null,
        isAcceptedRepayment: null,
        symbol: 'BTC',
        address: '0x7130d2A12B9BCbFAe4f2634d864A1Ee1Ce3Ead9c',
      },
      {
        id: 3,
        isWhitelistCollateral: true,
        isWhitelistSupply: false,
        usdExchange: null,
        isAcceptedAsCollateral: true,
        isAcceptedAsLoan: null,
        isAcceptedRepayment: null,
        symbol: 'ETH',
        address: '0x2170Ed0880ac9A755fd29B2688956BD959F933F8',
      },
      {
        id: 17,
        isWhitelistCollateral: true,
        isWhitelistSupply: false,
        usdExchange: null,
        isAcceptedAsCollateral: true,
        isAcceptedAsLoan: null,
        isAcceptedRepayment: null,
        symbol: 'FIL',
        address: '0x0D8Ce2A99Bb6e3B7Db580eD848240e4a0F9aE153',
      },
      {
        id: 22,
        isWhitelistCollateral: true,
        isWhitelistSupply: false,
        usdExchange: null,
        isAcceptedAsCollateral: true,
        isAcceptedAsLoan: null,
        isAcceptedRepayment: null,
        symbol: 'IOTX',
        address: '0x9678E42ceBEb63F23197D726B29b1CB20d0064E5',
      },
      {
        id: 23,
        isWhitelistCollateral: true,
        isWhitelistSupply: false,
        usdExchange: null,
        isAcceptedAsCollateral: true,
        isAcceptedAsLoan: null,
        isAcceptedRepayment: null,
        symbol: 'PAX',
        address: '0xb7F8Cd00C5A06c0537E2aBfF0b58033d02e5E094',
      },
      {
        id: 20,
        isWhitelistCollateral: true,
        isWhitelistSupply: false,
        usdExchange: null,
        isAcceptedAsCollateral: true,
        isAcceptedAsLoan: null,
        isAcceptedRepayment: null,
        symbol: 'ONT',
        address: '0xFd7B3A77848f1C2D67E05E54d78d174a0C850335',
      },
      {
        id: 21,
        isWhitelistCollateral: true,
        isWhitelistSupply: false,
        usdExchange: null,
        isAcceptedAsCollateral: true,
        isAcceptedAsLoan: null,
        isAcceptedRepayment: null,
        symbol: 'SNX',
        address: '0x9Ac983826058b8a9C7Aa1C9171441191232E8404',
      },
      {
        id: 26,
        isWhitelistCollateral: true,
        isWhitelistSupply: false,
        usdExchange: null,
        isAcceptedAsCollateral: true,
        isAcceptedAsLoan: null,
        isAcceptedRepayment: null,
        symbol: 'SXP',
        address: '0x47BEAd2563dCBf3bF2c9407fEa4dC236fAbA485A',
      },
      {
        id: 27,
        isWhitelistCollateral: true,
        isWhitelistSupply: false,
        usdExchange: null,
        isAcceptedAsCollateral: true,
        isAcceptedAsLoan: null,
        isAcceptedRepayment: null,
        symbol: 'BAND',
        address: '0xAD6cAEb32CD2c308980a548bD0Bc5AA4306c6c18',
      },
      {
        id: 34,
        isWhitelistCollateral: true,
        isWhitelistSupply: false,
        usdExchange: null,
        isAcceptedAsCollateral: true,
        isAcceptedAsLoan: null,
        isAcceptedRepayment: null,
        symbol: 'DOT',
        address: '0x7083609fCE4d1d8Dc0C979AAb8c869Ea2C873402',
      },
      {
        id: 35,
        isWhitelistCollateral: true,
        isWhitelistSupply: false,
        usdExchange: null,
        isAcceptedAsCollateral: true,
        isAcceptedAsLoan: null,
        isAcceptedRepayment: null,
        symbol: 'BEL',
        address: '0x8443f091997f06a61670B735ED92734F5628692F',
      },
      {
        id: 18,
        isWhitelistCollateral: true,
        isWhitelistSupply: false,
        usdExchange: null,
        isAcceptedAsCollateral: true,
        isAcceptedAsLoan: null,
        isAcceptedRepayment: null,
        symbol: 'ELF',
        address: '0xa3f020a5C92e15be13CAF0Ee5C95cF79585EeCC9',
      },
      {
        id: 19,
        isWhitelistCollateral: true,
        isWhitelistSupply: false,
        usdExchange: null,
        isAcceptedAsCollateral: true,
        isAcceptedAsLoan: null,
        isAcceptedRepayment: null,
        symbol: 'TCT',
        address: '0xCA0a9Df6a8cAD800046C1DDc5755810718b65C44',
      },
      {
        id: 14,
        isWhitelistCollateral: true,
        isWhitelistSupply: false,
        usdExchange: null,
        isAcceptedAsCollateral: true,
        isAcceptedAsLoan: null,
        isAcceptedRepayment: null,
        symbol: 'LINK',
        address: '0xF8A0BF9cF54Bb92F17374d9e9A321E6a111a51bD',
      },
      {
        id: 15,
        isWhitelistCollateral: true,
        isWhitelistSupply: false,
        usdExchange: null,
        isAcceptedAsCollateral: true,
        isAcceptedAsLoan: null,
        isAcceptedRepayment: null,
        symbol: 'ADA',
        address: '0x3EE2200Efb3400fAbB9AacF31297cBdD1d435D47',
      },
      {
        id: 12,
        isWhitelistCollateral: true,
        isWhitelistSupply: false,
        usdExchange: null,
        isAcceptedAsCollateral: true,
        isAcceptedAsLoan: null,
        isAcceptedRepayment: null,
        symbol: 'EOS',
        address: '0x56b6fB708fC5732DEC1Afc8D8556423A2EDcCbD6',
      },
      {
        id: 13,
        isWhitelistCollateral: true,
        isWhitelistSupply: false,
        usdExchange: null,
        isAcceptedAsCollateral: true,
        isAcceptedAsLoan: null,
        isAcceptedRepayment: null,
        symbol: 'BCH',
        address: '0x8fF795a6F4D97E7887C79beA79aba5cc76444aDf',
      },
      {
        id: 37,
        isWhitelistCollateral: true,
        isWhitelistSupply: false,
        usdExchange: null,
        isAcceptedAsCollateral: true,
        isAcceptedAsLoan: null,
        isAcceptedRepayment: null,
        symbol: 'INJ',
        address: '0xa2B726B1145A4773F68593CF171187d8EBe4d495',
      },
      {
        id: 36,
        isWhitelistCollateral: true,
        isWhitelistSupply: false,
        usdExchange: null,
        isAcceptedAsCollateral: true,
        isAcceptedAsLoan: null,
        isAcceptedRepayment: null,
        symbol: 'UNI',
        address: '0xBf5140A22578168FD562DCcF235E5D43A02ce9B1',
      },
      {
        id: 33,
        isWhitelistCollateral: true,
        isWhitelistSupply: false,
        usdExchange: null,
        isAcceptedAsCollateral: true,
        isAcceptedAsLoan: null,
        isAcceptedRepayment: null,
        symbol: 'NEAR',
        address: '0x1Fa4a73a3F0133f0025378af00236f3aBDEE5D63',
      },
      {
        id: 4,
        isWhitelistCollateral: true,
        isWhitelistSupply: false,
        usdExchange: null,
        isAcceptedAsCollateral: true,
        isAcceptedAsLoan: null,
        isAcceptedRepayment: null,
        symbol: 'WBNB',
        address: '0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c',
      },
      {
        id: 25,
        isWhitelistCollateral: true,
        isWhitelistSupply: false,
        usdExchange: null,
        isAcceptedAsCollateral: true,
        isAcceptedAsLoan: null,
        isAcceptedRepayment: null,
        symbol: 'ATOM',
        address: '0x0Eb3a705fc54725037CC9e008bDede697f62F335',
      },
      {
        id: 30,
        isWhitelistCollateral: true,
        isWhitelistSupply: false,
        usdExchange: null,
        isAcceptedAsCollateral: true,
        isAcceptedAsLoan: null,
        isAcceptedRepayment: null,
        symbol: 'COMP',
        address: '0x52CE071Bd9b1C4B00A0b92D298c512478CaD67e8',
      },
      {
        id: 31,
        isWhitelistCollateral: true,
        isWhitelistSupply: false,
        usdExchange: null,
        isAcceptedAsCollateral: true,
        isAcceptedAsLoan: null,
        isAcceptedRepayment: null,
        symbol: 'YFI',
        address: '0x88f1A5ae2A3BF98AEAF342D26B30a79438c9142e',
      },
      {
        id: 32,
        isWhitelistCollateral: true,
        isWhitelistSupply: false,
        usdExchange: null,
        isAcceptedAsCollateral: true,
        isAcceptedAsLoan: null,
        isAcceptedRepayment: null,
        symbol: 'YFII',
        address: '0x7F70642d88cf1C4a3a7abb072B53B929b653edA5',
      },
      {
        id: 16,
        isWhitelistCollateral: true,
        isWhitelistSupply: false,
        usdExchange: null,
        isAcceptedAsCollateral: true,
        isAcceptedAsLoan: null,
        isAcceptedRepayment: null,
        symbol: 'XTZ',
        address: '0x16939ef78684453bfDFb47825F8a5F714f12623a',
      },
    ],
    acceptableAssetsAsLoan: [
      {
        id: 5,
        isWhitelistCollateral: true,
        isWhitelistSupply: true,
        usdExchange: null,
        isAcceptedAsCollateral: null,
        isAcceptedAsLoan: true,
        isAcceptedRepayment: null,
        symbol: 'USDT',
        address: '0x55d398326f99059fF775485246999027B3197955',
      },
    ],
    isFavourite: null,
    interest: null,
    interestMin: 10,
    interestMax: 70,
    liquidationThreshold: 80,
    durationQtyType: 0,
    durationQtyMin: 1,
    durationQtyMax: 20,
    allowedLoanMax: 200000,
    allowedLoanMin: 10,
    loanToValue: 70,
    loanToValueMin: null,
    loanToValueMax: null,
  },
  {
    associatedWalletAddress: '0x87eb7808244dc63a1c9220be1fe018e0565a1427',
    id: 47,
    name: "Do you need USDT ? , Let's come to us",
    pawnShop: {
      id: 281,
      userId: 138,
      name: 'DFY Pawnshop Crypto',
      email: 'truonglv3892@gmail.com',
      phoneNumber: '+84989666888',
      address: 'Ha Noi - Viet Nam',
      description: 'DFY - Become Your Own Bank',
      avatar:
        'https://www.pioneerbnk.com/wp-content/uploads/2018/08/personalbanking.jpg',
      reputation: 0,
      isFeaturedPawnshop: true,
      type: 1,
      rank: null,
      associatedAddress: null,
      completedContracts: null,
      minInterestRate: null,
      maxInterestRate: null,
      createdAt: '2021-07-11T22:04:13.182+00:00',
      updatedAt: '2021-07-17T00:28:48.663+00:00',
      isDeleted: false,
      medals: null,
      p2PLenderPackages: null,
      coverImage:
        'https://s3.ap-southeast-1.amazonaws.com/staging-storage-dfy/upload/mountain.jpg',
    },
    type: 1,
    acceptableAssetsAsCollateral: [
      // {
      //   id: 38,
      //   isWhitelistCollateral: true,
      //   isWhitelistSupply: false,
      //   usdExchange: null,
      //   isAcceptedAsCollateral: true,
      //   isAcceptedAsLoan: null,
      //   isAcceptedRepayment: null,
      //   symbol: 'BNB',
      //   address: '0x0000000000000000000000000000000000000000',
      // },
      // {
      //   id: 8,
      //   isWhitelistCollateral: true,
      //   isWhitelistSupply: false,
      //   usdExchange: null,
      //   isAcceptedAsCollateral: true,
      //   isAcceptedAsLoan: null,
      //   isAcceptedRepayment: null,
      //   symbol: 'ETC',
      //   address: '0x3d6545b08693daE087E957cb1180ee38B9e3c25E',
      // },
      {
        id: 9,
        isWhitelistCollateral: true,
        isWhitelistSupply: false,
        usdExchange: null,
        isAcceptedAsCollateral: true,
        isAcceptedAsLoan: null,
        isAcceptedRepayment: null,
        symbol: 'ZEC',
        address: '0x1Ba42e5193dfA8B03D15dd1B86a3113bbBEF8Eeb',
      },
      {
        id: 6,
        isWhitelistCollateral: true,
        isWhitelistSupply: false,
        usdExchange: null,
        isAcceptedAsCollateral: true,
        isAcceptedAsLoan: null,
        isAcceptedRepayment: null,
        symbol: 'XRP',
        address: '0x1D2F0da169ceB9fC7B3144628dB156f3F6c60dBE',
      },
      {
        id: 7,
        isWhitelistCollateral: true,
        isWhitelistSupply: false,
        usdExchange: null,
        isAcceptedAsCollateral: true,
        isAcceptedAsLoan: null,
        isAcceptedRepayment: null,
        symbol: 'LTC',
        address: '0x4338665CBB7B2485A8855A139b75D5e34AB0DB94',
      },
      {
        id: 10,
        isWhitelistCollateral: true,
        isWhitelistSupply: false,
        usdExchange: null,
        isAcceptedAsCollateral: true,
        isAcceptedAsLoan: null,
        isAcceptedRepayment: null,
        symbol: 'MKR',
        address: '0x5f0Da599BB2ccCfcf6Fdfd7D81743B6020864350',
      },
      {
        id: 11,
        isWhitelistCollateral: true,
        isWhitelistSupply: false,
        usdExchange: null,
        isAcceptedAsCollateral: true,
        isAcceptedAsLoan: null,
        isAcceptedRepayment: null,
        symbol: 'BAT',
        address: '0x101d82428437127bF1608F699CD651e6Abf9766E',
      },
      {
        id: 2,
        isWhitelistCollateral: true,
        isWhitelistSupply: false,
        usdExchange: null,
        isAcceptedAsCollateral: true,
        isAcceptedAsLoan: null,
        isAcceptedRepayment: null,
        symbol: 'BTC',
        address: '0x7130d2A12B9BCbFAe4f2634d864A1Ee1Ce3Ead9c',
      },
      {
        id: 3,
        isWhitelistCollateral: true,
        isWhitelistSupply: false,
        usdExchange: null,
        isAcceptedAsCollateral: true,
        isAcceptedAsLoan: null,
        isAcceptedRepayment: null,
        symbol: 'ETH',
        address: '0x2170Ed0880ac9A755fd29B2688956BD959F933F8',
      },
      {
        id: 1,
        isWhitelistCollateral: true,
        isWhitelistSupply: true,
        usdExchange: null,
        isAcceptedAsCollateral: true,
        isAcceptedAsLoan: null,
        isAcceptedRepayment: true,
        symbol: 'DFY',
        address: '0xD98560689C6e748DC37bc410B4d3096B1aA3D8C2',
      },
      {
        id: 17,
        isWhitelistCollateral: true,
        isWhitelistSupply: false,
        usdExchange: null,
        isAcceptedAsCollateral: true,
        isAcceptedAsLoan: null,
        isAcceptedRepayment: null,
        symbol: 'FIL',
        address: '0x0D8Ce2A99Bb6e3B7Db580eD848240e4a0F9aE153',
      },
      {
        id: 22,
        isWhitelistCollateral: true,
        isWhitelistSupply: false,
        usdExchange: null,
        isAcceptedAsCollateral: true,
        isAcceptedAsLoan: null,
        isAcceptedRepayment: null,
        symbol: 'IOTX',
        address: '0x9678E42ceBEb63F23197D726B29b1CB20d0064E5',
      },
      {
        id: 23,
        isWhitelistCollateral: true,
        isWhitelistSupply: false,
        usdExchange: null,
        isAcceptedAsCollateral: true,
        isAcceptedAsLoan: null,
        isAcceptedRepayment: null,
        symbol: 'PAX',
        address: '0xb7F8Cd00C5A06c0537E2aBfF0b58033d02e5E094',
      },
      {
        id: 20,
        isWhitelistCollateral: true,
        isWhitelistSupply: false,
        usdExchange: null,
        isAcceptedAsCollateral: true,
        isAcceptedAsLoan: null,
        isAcceptedRepayment: null,
        symbol: 'ONT',
        address: '0xFd7B3A77848f1C2D67E05E54d78d174a0C850335',
      },
      {
        id: 21,
        isWhitelistCollateral: true,
        isWhitelistSupply: false,
        usdExchange: null,
        isAcceptedAsCollateral: true,
        isAcceptedAsLoan: null,
        isAcceptedRepayment: null,
        symbol: 'SNX',
        address: '0x9Ac983826058b8a9C7Aa1C9171441191232E8404',
      },
      {
        id: 26,
        isWhitelistCollateral: true,
        isWhitelistSupply: false,
        usdExchange: null,
        isAcceptedAsCollateral: true,
        isAcceptedAsLoan: null,
        isAcceptedRepayment: null,
        symbol: 'SXP',
        address: '0x47BEAd2563dCBf3bF2c9407fEa4dC236fAbA485A',
      },
      {
        id: 27,
        isWhitelistCollateral: true,
        isWhitelistSupply: false,
        usdExchange: null,
        isAcceptedAsCollateral: true,
        isAcceptedAsLoan: null,
        isAcceptedRepayment: null,
        symbol: 'BAND',
        address: '0xAD6cAEb32CD2c308980a548bD0Bc5AA4306c6c18',
      },
      {
        id: 34,
        isWhitelistCollateral: true,
        isWhitelistSupply: false,
        usdExchange: null,
        isAcceptedAsCollateral: true,
        isAcceptedAsLoan: null,
        isAcceptedRepayment: null,
        symbol: 'DOT',
        address: '0x7083609fCE4d1d8Dc0C979AAb8c869Ea2C873402',
      },
      {
        id: 35,
        isWhitelistCollateral: true,
        isWhitelistSupply: false,
        usdExchange: null,
        isAcceptedAsCollateral: true,
        isAcceptedAsLoan: null,
        isAcceptedRepayment: null,
        symbol: 'BEL',
        address: '0x8443f091997f06a61670B735ED92734F5628692F',
      },
      {
        id: 18,
        isWhitelistCollateral: true,
        isWhitelistSupply: false,
        usdExchange: null,
        isAcceptedAsCollateral: true,
        isAcceptedAsLoan: null,
        isAcceptedRepayment: null,
        symbol: 'ELF',
        address: '0xa3f020a5C92e15be13CAF0Ee5C95cF79585EeCC9',
      },
      {
        id: 19,
        isWhitelistCollateral: true,
        isWhitelistSupply: false,
        usdExchange: null,
        isAcceptedAsCollateral: true,
        isAcceptedAsLoan: null,
        isAcceptedRepayment: null,
        symbol: 'TCT',
        address: '0xCA0a9Df6a8cAD800046C1DDc5755810718b65C44',
      },
      {
        id: 14,
        isWhitelistCollateral: true,
        isWhitelistSupply: false,
        usdExchange: null,
        isAcceptedAsCollateral: true,
        isAcceptedAsLoan: null,
        isAcceptedRepayment: null,
        symbol: 'LINK',
        address: '0xF8A0BF9cF54Bb92F17374d9e9A321E6a111a51bD',
      },
      {
        id: 15,
        isWhitelistCollateral: true,
        isWhitelistSupply: false,
        usdExchange: null,
        isAcceptedAsCollateral: true,
        isAcceptedAsLoan: null,
        isAcceptedRepayment: null,
        symbol: 'ADA',
        address: '0x3EE2200Efb3400fAbB9AacF31297cBdD1d435D47',
      },
      {
        id: 12,
        isWhitelistCollateral: true,
        isWhitelistSupply: false,
        usdExchange: null,
        isAcceptedAsCollateral: true,
        isAcceptedAsLoan: null,
        isAcceptedRepayment: null,
        symbol: 'EOS',
        address: '0x56b6fB708fC5732DEC1Afc8D8556423A2EDcCbD6',
      },
      {
        id: 13,
        isWhitelistCollateral: true,
        isWhitelistSupply: false,
        usdExchange: null,
        isAcceptedAsCollateral: true,
        isAcceptedAsLoan: null,
        isAcceptedRepayment: null,
        symbol: 'BCH',
        address: '0x8fF795a6F4D97E7887C79beA79aba5cc76444aDf',
      },
      {
        id: 37,
        isWhitelistCollateral: true,
        isWhitelistSupply: false,
        usdExchange: null,
        isAcceptedAsCollateral: true,
        isAcceptedAsLoan: null,
        isAcceptedRepayment: null,
        symbol: 'INJ',
        address: '0xa2B726B1145A4773F68593CF171187d8EBe4d495',
      },
      {
        id: 36,
        isWhitelistCollateral: true,
        isWhitelistSupply: false,
        usdExchange: null,
        isAcceptedAsCollateral: true,
        isAcceptedAsLoan: null,
        isAcceptedRepayment: null,
        symbol: 'UNI',
        address: '0xBf5140A22578168FD562DCcF235E5D43A02ce9B1',
      },
      {
        id: 33,
        isWhitelistCollateral: true,
        isWhitelistSupply: false,
        usdExchange: null,
        isAcceptedAsCollateral: true,
        isAcceptedAsLoan: null,
        isAcceptedRepayment: null,
        symbol: 'NEAR',
        address: '0x1Fa4a73a3F0133f0025378af00236f3aBDEE5D63',
      },
      {
        id: 25,
        isWhitelistCollateral: true,
        isWhitelistSupply: false,
        usdExchange: null,
        isAcceptedAsCollateral: true,
        isAcceptedAsLoan: null,
        isAcceptedRepayment: null,
        symbol: 'ATOM',
        address: '0x0Eb3a705fc54725037CC9e008bDede697f62F335',
      },
      {
        id: 30,
        isWhitelistCollateral: true,
        isWhitelistSupply: false,
        usdExchange: null,
        isAcceptedAsCollateral: true,
        isAcceptedAsLoan: null,
        isAcceptedRepayment: null,
        symbol: 'COMP',
        address: '0x52CE071Bd9b1C4B00A0b92D298c512478CaD67e8',
      },
      {
        id: 31,
        isWhitelistCollateral: true,
        isWhitelistSupply: false,
        usdExchange: null,
        isAcceptedAsCollateral: true,
        isAcceptedAsLoan: null,
        isAcceptedRepayment: null,
        symbol: 'YFI',
        address: '0x88f1A5ae2A3BF98AEAF342D26B30a79438c9142e',
      },
      {
        id: 32,
        isWhitelistCollateral: true,
        isWhitelistSupply: false,
        usdExchange: null,
        isAcceptedAsCollateral: true,
        isAcceptedAsLoan: null,
        isAcceptedRepayment: null,
        symbol: 'YFII',
        address: '0x7F70642d88cf1C4a3a7abb072B53B929b653edA5',
      },
      {
        id: 16,
        isWhitelistCollateral: true,
        isWhitelistSupply: false,
        usdExchange: null,
        isAcceptedAsCollateral: true,
        isAcceptedAsLoan: null,
        isAcceptedRepayment: null,
        symbol: 'XTZ',
        address: '0x16939ef78684453bfDFb47825F8a5F714f12623a',
      },
      {
        id: 4,
        isWhitelistCollateral: true,
        isWhitelistSupply: false,
        usdExchange: null,
        isAcceptedAsCollateral: true,
        isAcceptedAsLoan: null,
        isAcceptedRepayment: null,
        symbol: 'WBNB',
        address: '0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c',
      },
    ],
    acceptableAssetsAsLoan: [
      {
        id: 5,
        isWhitelistCollateral: true,
        isWhitelistSupply: true,
        usdExchange: null,
        isAcceptedAsCollateral: null,
        isAcceptedAsLoan: true,
        isAcceptedRepayment: null,
        symbol: 'USDT',
        address: '0x55d398326f99059fF775485246999027B3197955',
      },
    ],
    isFavourite: null,
    interest: 30,
    interestMin: null,
    interestMax: null,
    liquidationThreshold: 80,
    durationQtyType: 0,
    durationQtyMin: 1,
    durationQtyMax: 10,
    allowedLoanMax: 10000,
    allowedLoanMin: 10,
    loanToValue: 70,
    loanToValueMin: null,
    loanToValueMax: null,
  },
  {
    associatedWalletAddress: '0x67faaac9b8222b6f1f4fdf50f9d4543bcab811c6',
    id: 76,
    name: "Do you need money ? , Let's come to us",
    pawnShop: {
      id: 281,
      userId: 138,
      name: 'DFY Pawnshop Crypto',
      email: 'truonglv3892@gmail.com',
      phoneNumber: '+84989666888',
      address: 'Ha Noi - Viet Nam',
      description: 'DFY - Become Your Own Bank',
      avatar:
        'https://www.pioneerbnk.com/wp-content/uploads/2018/08/personalbanking.jpg',
      reputation: 0,
      isFeaturedPawnshop: true,
      type: 1,
      rank: null,
      associatedAddress: null,
      completedContracts: null,
      minInterestRate: null,
      maxInterestRate: null,
      createdAt: '2021-07-11T22:04:13.182+00:00',
      updatedAt: '2021-07-17T00:28:48.663+00:00',
      isDeleted: false,
      medals: null,
      p2PLenderPackages: null,
      coverImage:
        'https://s3.ap-southeast-1.amazonaws.com/staging-storage-dfy/upload/mountain.jpg',
    },
    type: 0,
    acceptableAssetsAsCollateral: [
      {
        id: 38,
        isWhitelistCollateral: true,
        isWhitelistSupply: false,
        usdExchange: null,
        isAcceptedAsCollateral: true,
        isAcceptedAsLoan: null,
        isAcceptedRepayment: null,
        symbol: 'BNB',
        address: '0x0000000000000000000000000000000000000000',
      },
      {
        id: 8,
        isWhitelistCollateral: true,
        isWhitelistSupply: false,
        usdExchange: null,
        isAcceptedAsCollateral: true,
        isAcceptedAsLoan: null,
        isAcceptedRepayment: null,
        symbol: 'ETC',
        address: '0x3d6545b08693daE087E957cb1180ee38B9e3c25E',
      },
      {
        id: 9,
        isWhitelistCollateral: true,
        isWhitelistSupply: false,
        usdExchange: null,
        isAcceptedAsCollateral: true,
        isAcceptedAsLoan: null,
        isAcceptedRepayment: null,
        symbol: 'ZEC',
        address: '0x1Ba42e5193dfA8B03D15dd1B86a3113bbBEF8Eeb',
      },
      {
        id: 6,
        isWhitelistCollateral: true,
        isWhitelistSupply: false,
        usdExchange: null,
        isAcceptedAsCollateral: true,
        isAcceptedAsLoan: null,
        isAcceptedRepayment: null,
        symbol: 'XRP',
        address: '0x1D2F0da169ceB9fC7B3144628dB156f3F6c60dBE',
      },
      {
        id: 7,
        isWhitelistCollateral: true,
        isWhitelistSupply: false,
        usdExchange: null,
        isAcceptedAsCollateral: true,
        isAcceptedAsLoan: null,
        isAcceptedRepayment: null,
        symbol: 'LTC',
        address: '0x4338665CBB7B2485A8855A139b75D5e34AB0DB94',
      },
      {
        id: 10,
        isWhitelistCollateral: true,
        isWhitelistSupply: false,
        usdExchange: null,
        isAcceptedAsCollateral: true,
        isAcceptedAsLoan: null,
        isAcceptedRepayment: null,
        symbol: 'MKR',
        address: '0x5f0Da599BB2ccCfcf6Fdfd7D81743B6020864350',
      },
      {
        id: 11,
        isWhitelistCollateral: true,
        isWhitelistSupply: false,
        usdExchange: null,
        isAcceptedAsCollateral: true,
        isAcceptedAsLoan: null,
        isAcceptedRepayment: null,
        symbol: 'BAT',
        address: '0x101d82428437127bF1608F699CD651e6Abf9766E',
      },
      {
        id: 2,
        isWhitelistCollateral: true,
        isWhitelistSupply: false,
        usdExchange: null,
        isAcceptedAsCollateral: true,
        isAcceptedAsLoan: null,
        isAcceptedRepayment: null,
        symbol: 'BTC',
        address: '0x7130d2A12B9BCbFAe4f2634d864A1Ee1Ce3Ead9c',
      },
      {
        id: 3,
        isWhitelistCollateral: true,
        isWhitelistSupply: false,
        usdExchange: null,
        isAcceptedAsCollateral: true,
        isAcceptedAsLoan: null,
        isAcceptedRepayment: null,
        symbol: 'ETH',
        address: '0x2170Ed0880ac9A755fd29B2688956BD959F933F8',
      },
      {
        id: 1,
        isWhitelistCollateral: true,
        isWhitelistSupply: true,
        usdExchange: null,
        isAcceptedAsCollateral: true,
        isAcceptedAsLoan: null,
        isAcceptedRepayment: null,
        symbol: 'DFY',
        address: '0xD98560689C6e748DC37bc410B4d3096B1aA3D8C2',
      },
      {
        id: 17,
        isWhitelistCollateral: true,
        isWhitelistSupply: false,
        usdExchange: null,
        isAcceptedAsCollateral: true,
        isAcceptedAsLoan: null,
        isAcceptedRepayment: null,
        symbol: 'FIL',
        address: '0x0D8Ce2A99Bb6e3B7Db580eD848240e4a0F9aE153',
      },
      {
        id: 22,
        isWhitelistCollateral: true,
        isWhitelistSupply: false,
        usdExchange: null,
        isAcceptedAsCollateral: true,
        isAcceptedAsLoan: null,
        isAcceptedRepayment: null,
        symbol: 'IOTX',
        address: '0x9678E42ceBEb63F23197D726B29b1CB20d0064E5',
      },
      {
        id: 23,
        isWhitelistCollateral: true,
        isWhitelistSupply: false,
        usdExchange: null,
        isAcceptedAsCollateral: true,
        isAcceptedAsLoan: null,
        isAcceptedRepayment: null,
        symbol: 'PAX',
        address: '0xb7F8Cd00C5A06c0537E2aBfF0b58033d02e5E094',
      },
      {
        id: 20,
        isWhitelistCollateral: true,
        isWhitelistSupply: false,
        usdExchange: null,
        isAcceptedAsCollateral: true,
        isAcceptedAsLoan: null,
        isAcceptedRepayment: null,
        symbol: 'ONT',
        address: '0xFd7B3A77848f1C2D67E05E54d78d174a0C850335',
      },
      {
        id: 21,
        isWhitelistCollateral: true,
        isWhitelistSupply: false,
        usdExchange: null,
        isAcceptedAsCollateral: true,
        isAcceptedAsLoan: null,
        isAcceptedRepayment: null,
        symbol: 'SNX',
        address: '0x9Ac983826058b8a9C7Aa1C9171441191232E8404',
      },
      {
        id: 26,
        isWhitelistCollateral: true,
        isWhitelistSupply: false,
        usdExchange: null,
        isAcceptedAsCollateral: true,
        isAcceptedAsLoan: null,
        isAcceptedRepayment: null,
        symbol: 'SXP',
        address: '0x47BEAd2563dCBf3bF2c9407fEa4dC236fAbA485A',
      },
      {
        id: 27,
        isWhitelistCollateral: true,
        isWhitelistSupply: false,
        usdExchange: null,
        isAcceptedAsCollateral: true,
        isAcceptedAsLoan: null,
        isAcceptedRepayment: null,
        symbol: 'BAND',
        address: '0xAD6cAEb32CD2c308980a548bD0Bc5AA4306c6c18',
      },
      {
        id: 34,
        isWhitelistCollateral: true,
        isWhitelistSupply: false,
        usdExchange: null,
        isAcceptedAsCollateral: true,
        isAcceptedAsLoan: null,
        isAcceptedRepayment: null,
        symbol: 'DOT',
        address: '0x7083609fCE4d1d8Dc0C979AAb8c869Ea2C873402',
      },
      {
        id: 35,
        isWhitelistCollateral: true,
        isWhitelistSupply: false,
        usdExchange: null,
        isAcceptedAsCollateral: true,
        isAcceptedAsLoan: null,
        isAcceptedRepayment: null,
        symbol: 'BEL',
        address: '0x8443f091997f06a61670B735ED92734F5628692F',
      },
      {
        id: 18,
        isWhitelistCollateral: true,
        isWhitelistSupply: false,
        usdExchange: null,
        isAcceptedAsCollateral: true,
        isAcceptedAsLoan: null,
        isAcceptedRepayment: null,
        symbol: 'ELF',
        address: '0xa3f020a5C92e15be13CAF0Ee5C95cF79585EeCC9',
      },
      {
        id: 19,
        isWhitelistCollateral: true,
        isWhitelistSupply: false,
        usdExchange: null,
        isAcceptedAsCollateral: true,
        isAcceptedAsLoan: null,
        isAcceptedRepayment: null,
        symbol: 'TCT',
        address: '0xCA0a9Df6a8cAD800046C1DDc5755810718b65C44',
      },
      {
        id: 14,
        isWhitelistCollateral: true,
        isWhitelistSupply: false,
        usdExchange: null,
        isAcceptedAsCollateral: true,
        isAcceptedAsLoan: null,
        isAcceptedRepayment: null,
        symbol: 'LINK',
        address: '0xF8A0BF9cF54Bb92F17374d9e9A321E6a111a51bD',
      },
      {
        id: 15,
        isWhitelistCollateral: true,
        isWhitelistSupply: false,
        usdExchange: null,
        isAcceptedAsCollateral: true,
        isAcceptedAsLoan: null,
        isAcceptedRepayment: null,
        symbol: 'ADA',
        address: '0x3EE2200Efb3400fAbB9AacF31297cBdD1d435D47',
      },
      {
        id: 12,
        isWhitelistCollateral: true,
        isWhitelistSupply: false,
        usdExchange: null,
        isAcceptedAsCollateral: true,
        isAcceptedAsLoan: null,
        isAcceptedRepayment: null,
        symbol: 'EOS',
        address: '0x56b6fB708fC5732DEC1Afc8D8556423A2EDcCbD6',
      },
      {
        id: 13,
        isWhitelistCollateral: true,
        isWhitelistSupply: false,
        usdExchange: null,
        isAcceptedAsCollateral: true,
        isAcceptedAsLoan: null,
        isAcceptedRepayment: null,
        symbol: 'BCH',
        address: '0x8fF795a6F4D97E7887C79beA79aba5cc76444aDf',
      },
      {
        id: 37,
        isWhitelistCollateral: true,
        isWhitelistSupply: false,
        usdExchange: null,
        isAcceptedAsCollateral: true,
        isAcceptedAsLoan: null,
        isAcceptedRepayment: null,
        symbol: 'INJ',
        address: '0xa2B726B1145A4773F68593CF171187d8EBe4d495',
      },
      {
        id: 36,
        isWhitelistCollateral: true,
        isWhitelistSupply: false,
        usdExchange: null,
        isAcceptedAsCollateral: true,
        isAcceptedAsLoan: null,
        isAcceptedRepayment: null,
        symbol: 'UNI',
        address: '0xBf5140A22578168FD562DCcF235E5D43A02ce9B1',
      },
      {
        id: 33,
        isWhitelistCollateral: true,
        isWhitelistSupply: false,
        usdExchange: null,
        isAcceptedAsCollateral: true,
        isAcceptedAsLoan: null,
        isAcceptedRepayment: null,
        symbol: 'NEAR',
        address: '0x1Fa4a73a3F0133f0025378af00236f3aBDEE5D63',
      },
      {
        id: 25,
        isWhitelistCollateral: true,
        isWhitelistSupply: false,
        usdExchange: null,
        isAcceptedAsCollateral: true,
        isAcceptedAsLoan: null,
        isAcceptedRepayment: null,
        symbol: 'ATOM',
        address: '0x0Eb3a705fc54725037CC9e008bDede697f62F335',
      },
      {
        id: 30,
        isWhitelistCollateral: true,
        isWhitelistSupply: false,
        usdExchange: null,
        isAcceptedAsCollateral: true,
        isAcceptedAsLoan: null,
        isAcceptedRepayment: null,
        symbol: 'COMP',
        address: '0x52CE071Bd9b1C4B00A0b92D298c512478CaD67e8',
      },
      {
        id: 31,
        isWhitelistCollateral: true,
        isWhitelistSupply: false,
        usdExchange: null,
        isAcceptedAsCollateral: true,
        isAcceptedAsLoan: null,
        isAcceptedRepayment: null,
        symbol: 'YFI',
        address: '0x88f1A5ae2A3BF98AEAF342D26B30a79438c9142e',
      },
      {
        id: 32,
        isWhitelistCollateral: true,
        isWhitelistSupply: false,
        usdExchange: null,
        isAcceptedAsCollateral: true,
        isAcceptedAsLoan: null,
        isAcceptedRepayment: null,
        symbol: 'YFII',
        address: '0x7F70642d88cf1C4a3a7abb072B53B929b653edA5',
      },
      {
        id: 16,
        isWhitelistCollateral: true,
        isWhitelistSupply: false,
        usdExchange: null,
        isAcceptedAsCollateral: true,
        isAcceptedAsLoan: null,
        isAcceptedRepayment: null,
        symbol: 'XTZ',
        address: '0x16939ef78684453bfDFb47825F8a5F714f12623a',
      },
      {
        id: 4,
        isWhitelistCollateral: true,
        isWhitelistSupply: false,
        usdExchange: null,
        isAcceptedAsCollateral: true,
        isAcceptedAsLoan: null,
        isAcceptedRepayment: null,
        symbol: 'WBNB',
        address: '0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c',
      },
    ],
    acceptableAssetsAsLoan: [
      {
        id: 5,
        isWhitelistCollateral: true,
        isWhitelistSupply: true,
        usdExchange: null,
        isAcceptedAsCollateral: null,
        isAcceptedAsLoan: true,
        isAcceptedRepayment: true,
        symbol: 'USDT',
        address: '0x55d398326f99059fF775485246999027B3197955',
      },
    ],
    isFavourite: null,
    interest: 17,
    interestMin: null,
    interestMax: null,
    liquidationThreshold: 80,
    durationQtyType: 0,
    durationQtyMin: 1,
    durationQtyMax: 10,
    allowedLoanMax: 1500,
    allowedLoanMin: 10,
    loanToValue: 70,
    loanToValueMin: null,
    loanToValueMax: null,
  },
];

export const FakeListItemSearchLendNFT = [
  {
    id: 212,
    nftId: 4,
    nftStatus: 1,
    nftType: 0,
    bcNftId: 3,
    bcCollateralId: 8,
    nftName: 'Stunning Sapphire',
    borrowerWalletAddress: '0x361f7903012a5fcbf021ed5d6e3afb6d3f8d0a73',
    reputation: null,
    durationTime: 12,
    durationType: 0,
    nftAssetLocation: 'Hà Nội',
    nftEvaluatedPrice: 270333,
    nftEvaluatedSymbol: 'USDT',
    expectedLoanAmount: 270333,
    expectedLoanSymbol: 'USDT',
    nftAssetTypeId: 1,
    nftAvatarCid: 'QmWtZ5KsaRrTGZmjLRn3AWS7ZVLvXHSoJH6A5KjU6W98wa',
    nftMediaCid: 'QmWtZ5KsaRrTGZmjLRn3AWS7ZVLvXHSoJH6A5KjU6W98wa',
  },
  {
    id: 215,
    nftId: 8,
    nftStatus: 1,
    nftType: 0,
    bcNftId: 7,
    bcCollateralId: 11,
    nftName: 'Aquatastic',
    borrowerWalletAddress: '0x361f7903012a5fcbf021ed5d6e3afb6d3f8d0a73',
    reputation: null,
    durationTime: 4,
    durationType: 0,
    nftAssetLocation: 'Hà Nội',
    nftEvaluatedPrice: 13350,
    nftEvaluatedSymbol: 'USDT',
    expectedLoanAmount: 13350,
    expectedLoanSymbol: 'USDT',
    nftAssetTypeId: 1,
    nftAvatarCid: 'QmU4zSvkukEH8UM1x1VMsUS7jxd8A9FoLUveQWRRNgaFgU',
    nftMediaCid: 'QmU4zSvkukEH8UM1x1VMsUS7jxd8A9FoLUveQWRRNgaFgU',
  },
  {
    id: 218,
    nftId: 11,
    nftStatus: 1,
    nftType: 0,
    bcNftId: 9,
    bcCollateralId: 14,
    nftName: 'Brownish Sparkling',
    borrowerWalletAddress: '0x361f7903012a5fcbf021ed5d6e3afb6d3f8d0a73',
    reputation: null,
    durationTime: 12,
    durationType: 0,
    nftAssetLocation: 'Hà Nội',
    nftEvaluatedPrice: 38000,
    nftEvaluatedSymbol: 'USDT',
    expectedLoanAmount: 38000,
    expectedLoanSymbol: 'USDT',
    nftAssetTypeId: 1,
    nftAvatarCid: 'QmZH5uHLz1UXNFysaaP5a9vhgpmWYyXQGKW6ZHdkXtpEDt',
    nftMediaCid: 'QmZH5uHLz1UXNFysaaP5a9vhgpmWYyXQGKW6ZHdkXtpEDt',
  },
];
